services:
  mysql:
    image: mysql:8.0
    container_name: health-mysql
    environment:
      MYSQL_ROOT_PASSWORD: SEU_CSE
      MYSQL_DATABASE: health_assistant
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/models/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: health-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
